### ISSUE TITLE
ModuleNotFoundError: No module named 'mermaid'

### ISSUE THREAD

**Issue by VariableXX** [uncbiag/easyreg#13]
I try to run ./demo/demo_for_easyreg_eval.py via python ./demo_for_easyreg_eval.py --setting_folder_path ./demo_settings/mermaid/opt_vsvf --gpu_id 0  --task_output_path ./demo_output/mermaid/
opt_vsvf -s ./image/image_1_save.nii.gz -t ./image/image_2_save.nii.gz.

However, the error had been occurred :
Traceback (most recent call last):
  File "./demo_for_easyreg_eval.py", line 247, in <module>
    do_registration_eval(args, registration_pair_list, pair_name_list)
  File "./demo_for_easyreg_eval.py", line 162, in do_registration_eval
    run_one_task(tsm_json_path, dm_json_path)
  File "D:\Python_Code\easyreg\easyreg\piplines.py", line 58, in run_one_task
    pipline.initialize(task_setting_pth,data_setting_pth,data_loaders)
  File "D:\Python_Code\easyreg\easyreg\piplines.py", line 28, in initialize
    self.model = create_model(self.tsk_opt)
  File "D:\Python_Code\easyreg\easyreg\create_model.py", line 29, in create_model
    from .mermaid_iter import MermaidIter
  File "D:\Python_Code\easyreg\easyreg\mermaid_iter.py", line 1, in <module>
    from .base_mermaid import MermaidBase
  File "D:\Python_Code\easyreg\easyreg\base_mermaid.py", line 2, in <module>
    from .base_reg_model import RegModelBase
  File "D:\Python_Code\easyreg\easyreg\base_reg_model.py", line 2, in <module>
    from .utils import *
  File "D:\Python_Code\easyreg\easyreg\utils.py", line 7, in <module>
    import mermaid.image_sampling as py_is
ModuleNotFoundError: No module named 'mermaid'

Ana I can't found this file in this project.

**Comment by VariableXX** [comment]
I can't found mermaid.py in this project.

**Comment by dzenanz** [comment]
Did you look in https://github.com/uncbiag/mermaid?
